name: Node.js Package

on:
  release:
    types: [published]

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build the application
        run: npm run build

      - name: Test the application
        run: npm test

      - name: Build the package
        run: |
          npm pack dist/
          mv zxing-browser-*.tgz package.tgz

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pack-artifact
          path: ./package.tgz

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: pack-artifact
          path: pack-artifact

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/

      - run: npm publish ./pack-artifact/package.tgz
